FROM golang:1.17.5-alpine as builder

WORKDIR /go/src/app

ENV GO111MODULE=on

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

FROM alpine

COPY --from=builder /go/bin/app /go/bin/app

EXPOSE 8080

CMD ["/go/bin/app"]
